spring.application.name=movieRecommendation

spring.datasource.url=jdbc:postgresql://localhost:5432/moviesdb
spring.datasource.username=postgres
spring.datasource.password=2004

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

#tmdb.api.key=64dd476ecf005e5db15b11101df96a86

